# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-06 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20180607_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
