# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-07 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20180607_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
