# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-07 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_auto_20180607_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='deposit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='total',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='withdraw',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
